---
title: "Homework 2 (p8105)"
author: "Britney Mazzetta (blm2156)"
output: github_document
---

# Problem 1

## Mr. Trash Wheel
```{r}
library(tidyverse)
library(readxl)

prob1 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
  sheet = 1, range = "A2:N338") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sport_balls = as.integer(sports_balls)) %>%
  select(-sports_balls)

```

## 2017 Precipitation
```{r}
precip2017 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
  sheet = 6, range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(
    Year = 2017
    )
```

## 2018 Precipitation
```{r}
precip2018 = 
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", 
  sheet = 5, range = "A2:B14") %>%
  janitor::clean_names() %>%
  mutate(
    Year = 2018
    )
```

## Combine Datasets

```{r}
combined_data =
  bind_rows(precip2017, precip2018) %>%
  mutate(
    month = as.numeric(month),
    month = month.name[month]
  )
  
```


